version: "3.5"

services:
  test_postgres:
    image: "postgres:latest"
    container_name: test_postgres
    ports:
      - "13081:5432"
    volumes:
      - ./dev/SQL:/docker-entrypoint-initdb.d/
      - ./dev/log:/var/log/
    environment:
      POSTGRES_USER: uliana
      POSTGRES_DB: filmoteka
      POSTGRES_PASSWORD: uliana
    networks:
      - mynetwork

  redis-session:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  app:
    build: .
    container_name: app
    restart: always
    depends_on: 
      - test_postgres
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
  default:
    external:
      name: mynetwork